version: '2.1'

services:
  product:
    build: microservices/product-service
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  phone:
    build: microservices/phone-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  eureka:
    build: spring-cloud/eureka-server
    mem_limit: 350m
    ports:
      - "8761:8761"

