AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: "The Best Phone Service on the World"

Parameters:
  EnvironmentName:
    Type: String
    Default: demo

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 300
    Handler: index.handler
    Environment:
      Variables:
        VOUCHER_RESULT_SQS_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${EnvironmentName}_voucher_result"
        VOUCHER_ORDER_SQS_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${EnvironmentName}_voucher_order"
        AUTH_TIMER_SQS_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${EnvironmentName}_timer"
        AUTH_TIMER_EXPIRED_SQS_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${EnvironmentName}_timer_expired"
        SMS_SQS_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${EnvironmentName}_sms"
        TWILIO_ACCOUNT_SID: xxxxxxxx
        TWILIO_ACCOUNT_AUTH: xxxxxxxxxx
        TWILIO_PHONE_NUMBER: "+xxxxx"

        
Resources:
  GetVoucher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/get-voucher/get-voucher.zip
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Join ["_",[!Ref EnvironmentName , "voucher_result"]]
      Events:
        VoucherOrderCome:
          Type: SQS
          Properties:
            Queue:  !GetAtt VoucherOrderQueue.Arn
            BatchSize: 1

  VoucherResultQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["_",[!Ref EnvironmentName , "voucher_result"]]
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt VoucherOrderResultDeadQueue.Arn
        maxReceiveCount: 5

  VoucherOrderResultDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["_",[!Ref EnvironmentName , "voucher_order_result_dead"]]
      VisibilityTimeout: 300

  VoucherOrderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["_",[!Ref EnvironmentName , "voucher_order"]]
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt VoucherOrderDeadQueue.Arn
        maxReceiveCount: 5

  VoucherOrderDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["_",[!Ref EnvironmentName , "voucher_order_dead"]]
      VisibilityTimeout: 300

  SendSMS:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/send-sms/send-sms.zip
      Policies:
        - Statement:
            - Action:
              - sns:Publish
              Effect: Allow
              Resource: "*"
      Events:
        SMSMessageCome:
          Type: SQS
          Properties:
            Queue:  !GetAtt SMSQueue.Arn
            BatchSize: 1

  SMSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["_",[!Ref EnvironmentName , "sms"]]
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SMSDeadQueue.Arn
        maxReceiveCount: 5

  SMSDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["_",[!Ref EnvironmentName , "sms_dead"]]
      VisibilityTimeout: 300

  AuthTimerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/auth-timer/auth-timer.zip
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Join ["_",[!Ref EnvironmentName , "timer_expired"]]
      Events:
        VoucherOrderCome:
          Type: SQS
          Properties:
            Queue:  !GetAtt AuthTimerQueue.Arn
            BatchSize: 1

  AuthTimerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["_",[!Ref EnvironmentName , "timer"]]
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt AuthTimerDeadQueue.Arn
        maxReceiveCount: 5

  AuthTimerDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["_",[!Ref EnvironmentName , "timer_dead"]]
      VisibilityTimeout: 300
  
  AuthTimerExpiredQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["_",[!Ref EnvironmentName , "timer_expired"]]
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt AuthTimerExpiredDeadQueue.Arn
        maxReceiveCount: 5

  AuthTimerExpiredDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["_",[!Ref EnvironmentName , "timer_expired_dead"]]
      VisibilityTimeout: 300
