server:
  port: 7071

spring.application.name: phone

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
---
spring.profiles: docker

server.port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/