server:
  port: 8081

spring.application.name: phone

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost:3306/phone-db
  username: root
  password:

spring.datasource.hikari.initializationFailTimeout: 60000

application:
  mockSpeed: true
  queue:
    order: ${env.name}_voucher_order
    result: ${env.name}_voucher_result
    sms: ${env.name}_sms
    authTimer:  ${env.name}_timer
    authTimerExpired:  ${env.name}_timer_expired
---
spring.profiles: docker

server.port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/


spring:
  datasource:
    url: jdbc:mysql://mysql:3306/phone-db
    username: user
    password: pwd
